import type {
  AppNotification,
  AppUser,
  Dataset,
  FinancialEntry,
  FuelLog,
  MaintenanceRecord,
  MotorcycleFine,
  MotorcycleTrip,
  OilChange,
  PartStock,
  ServiceMotorcycle,
  StockMovement,
  Supplier,
  Vehicle,
  ActivityLog,
  AuditTrailEntry,
  Attachment,
  BackupRecord,
  CompanySettings,
  DeletedItem,
} from "@/lib/types";

export const demoUsers: AppUser[] = [
  {
    id: "user-admin",
    name: "Administrador",
    email: "admin@coopfleet.com",
    role: "ADMIN",
  },
];

export const demoVehicles: Vehicle[] = [
  {
    id: "veh-001",
    name: "Van Executiva 01",
    model: "Mercedes-Benz Sprinter 416",
    plate: "RTA4C21",
    year: 2023,
    driver: "Carlos Menezes",
    entryDate: "2025-02-12",
    status: "ACTIVE",
    mileage: 84320,
  },
  {
    id: "veh-002",
    name: "Micro-ônibus Urbano",
    model: "Volare Attack 9",
    plate: "QPL8D90",
    year: 2021,
    driver: "Marina Duarte",
    entryDate: "2024-08-04",
    status: "MAINTENANCE",
    mileage: 132900,
  },
  {
    id: "veh-003",
    name: "Utilitário Logístico",
    model: "Fiat Ducato Cargo",
    plate: "HJK7A55",
    year: 2022,
    driver: "Renato Lima",
    entryDate: "2024-11-18",
    status: "ACTIVE",
    mileage: 61240,
  },
  {
    id: "veh-004",
    name: "Van Escolar 04",
    model: "Renault Master L3H2",
    plate: "MNB2E18",
    year: 2020,
    driver: "Bianca Rocha",
    entryDate: "2023-06-22",
    status: "ALERT",
    mileage: 149870,
  },
  {
    id: "veh-005",
    name: "Furgão Refrigerado",
    model: "Iveco Daily 35-150",
    plate: "KLA9F33",
    year: 2024,
    driver: "João Barcelos",
    entryDate: "2025-10-09",
    status: "ACTIVE",
    mileage: 28840,
  },
  {
    id: "veh-006",
    name: "Pickup Operacional",
    model: "Toyota Hilux SRV",
    plate: "GFT1B70",
    year: 2022,
    driver: "Daniela Torres",
    entryDate: "2025-01-15",
    status: "ACTIVE",
    mileage: 73510,
  },
];

export const demoSuppliers: Supplier[] = [
  {
    id: "sup-001",
    name: "Auto Peças Central",
    contact: "Marta Souza",
    email: "compras@autopecascentral.com",
    phone: "(11) 4002-1180",
    document: "12.784.990/0001-40",
  },
  {
    id: "sup-002",
    name: "LubriMax Distribuidora",
    contact: "Rafael Coelho",
    email: "atendimento@lubrimax.com",
    phone: "(31) 3300-9088",
    document: "08.330.115/0001-21",
  },
  {
    id: "sup-003",
    name: "Pneus Norte Sul",
    contact: "Helena Prado",
    email: "vendas@pneusnortesul.com",
    phone: "(41) 3020-4410",
    document: "33.901.004/0001-17",
  },
];

export const demoPartStock: PartStock[] = [
  {
    id: "part-001",
    name: "Filtro de óleo Sprinter",
    category: "Filtros",
    sku: "FLT-SPR-001",
    manufacturer: "Mann Filter",
    quantity: 14,
    minQuantity: 8,
    unitCost: 74.9,
    entryDate: "2026-04-18",
    supplierId: "sup-001",
    notes: "Item de giro para revisoes preventivas.",
    lastEntryDate: "2026-04-18",
    supplierName: "Auto Peças Central",
  },
  {
    id: "part-002",
    name: "Pastilha de freio dianteira",
    category: "Freios",
    sku: "PST-FRD-020",
    manufacturer: "Fras-le",
    quantity: 5,
    minQuantity: 10,
    unitCost: 189.5,
    entryDate: "2026-05-03",
    supplierId: "sup-001",
    notes: "Priorizar reposicao por alto consumo.",
    lastEntryDate: "2026-05-03",
    supplierName: "Auto Peças Central",
  },
  {
    id: "part-003",
    name: "Pneu 225/75 R16",
    category: "Pneus",
    sku: "PNE-225-75",
    manufacturer: "Goodyear",
    quantity: 8,
    minQuantity: 6,
    unitCost: 779.9,
    entryDate: "2026-03-08",
    supplierId: "sup-003",
    notes: "Usar em vans e furgoes compativeis.",
    lastEntryDate: "2026-03-08",
    supplierName: "Pneus Norte Sul",
  },
  {
    id: "part-004",
    name: "Óleo 15W40 Diesel",
    category: "Lubrificantes",
    sku: "OLE-15W40-D",
    manufacturer: "Shell",
    quantity: 38,
    minQuantity: 24,
    unitCost: 31.8,
    entryDate: "2026-04-26",
    supplierId: "sup-002",
    notes: "Controle por litro em manutencoes e trocas.",
    lastEntryDate: "2026-04-26",
    supplierName: "LubriMax Distribuidora",
  },
  {
    id: "part-005",
    name: "Correia dentada",
    category: "Motor",
    sku: "COR-DNT-110",
    manufacturer: "Gates",
    quantity: 3,
    minQuantity: 5,
    unitCost: 264.75,
    entryDate: "2026-02-17",
    supplierId: "sup-001",
    notes: "Produto acabando; cotar nova compra.",
    lastEntryDate: "2026-02-17",
    supplierName: "Auto Peças Central",
  },
  {
    id: "part-006",
    name: "Amortecedor traseiro",
    category: "Suspensao",
    sku: "AMT-TRS-045",
    manufacturer: "Monroe",
    quantity: 7,
    minQuantity: 4,
    unitCost: 418,
    entryDate: "2026-01-28",
    supplierId: "sup-001",
    notes: "Compatibilidade conferida com frota operacional.",
    lastEntryDate: "2026-01-28",
    supplierName: "Auto Peças Central",
  },
];

export const demoStockMovements: StockMovement[] = [
  {
    id: "stk-001",
    partStockId: "part-001",
    partName: "Filtro de oleo Sprinter",
    kind: "IN",
    quantity: 18,
    unitCost: 74.9,
    totalValue: 1348.2,
    date: "2026-04-18",
    purchaseDate: "2026-04-18",
    supplierId: "sup-001",
    supplierName: "Auto Pecas Central",
    invoiceNumber: "NF-10482",
    responsibleUser: "Administrador",
    notes: "Reposicao preventiva.",
    createdAt: "2026-04-18",
  },
  {
    id: "stk-002",
    partStockId: "part-002",
    partName: "Pastilha de freio dianteira",
    kind: "IN",
    quantity: 16,
    unitCost: 189.5,
    totalValue: 3032,
    date: "2026-05-03",
    purchaseDate: "2026-05-03",
    supplierId: "sup-001",
    supplierName: "Auto Pecas Central",
    invoiceNumber: "NF-10501",
    responsibleUser: "Administrador",
    notes: "Compra com alerta de estoque baixo.",
    createdAt: "2026-05-03",
  },
  {
    id: "stk-003",
    partStockId: "part-003",
    partName: "Pneu 225/75 R16",
    kind: "IN",
    quantity: 12,
    unitCost: 779.9,
    totalValue: 9358.8,
    date: "2026-03-08",
    purchaseDate: "2026-03-08",
    supplierId: "sup-003",
    supplierName: "Pneus Norte Sul",
    invoiceNumber: "NF-8840",
    responsibleUser: "Administrador",
    notes: "Entrada para manutencoes de marco.",
    createdAt: "2026-03-08",
  },
  {
    id: "stk-004",
    partStockId: "part-004",
    partName: "Oleo 15W40 Diesel",
    kind: "IN",
    quantity: 50,
    unitCost: 31.8,
    totalValue: 1590,
    date: "2026-04-26",
    purchaseDate: "2026-04-26",
    supplierId: "sup-002",
    supplierName: "LubriMax Distribuidora",
    invoiceNumber: "NF-4412",
    responsibleUser: "Administrador",
    notes: "Reposicao mensal.",
    createdAt: "2026-04-26",
  },
  {
    id: "stk-005",
    partStockId: "part-002",
    partName: "Pastilha de freio dianteira",
    kind: "OUT",
    quantity: 6,
    unitCost: 205,
    totalValue: 1230,
    date: "2026-05-06",
    responsibleUser: "Oficina Nova Rota",
    maintenanceId: "mnt-001",
    notes: "Saida integrada a manutencao.",
    createdAt: "2026-05-06",
  },
  {
    id: "stk-006",
    partStockId: "part-006",
    partName: "Amortecedor traseiro",
    kind: "OUT",
    quantity: 4,
    unitCost: 480,
    totalValue: 1920,
    date: "2026-05-06",
    responsibleUser: "Oficina Nova Rota",
    maintenanceId: "mnt-001",
    notes: "Saida integrada a manutencao.",
    createdAt: "2026-05-06",
  },
];

export const demoMaintenances: MaintenanceRecord[] = [
  {
    id: "mnt-001",
    vehicleId: "veh-002",
    vehicleName: "Micro-ônibus Urbano",
    date: "2026-05-06",
    type: "Corretiva",
    mechanic: "Oficina Nova Rota",
    notes: "Substituição do conjunto de freio e revisão de suspensão.",
    totalValue: 3849,
    parts: [
      {
        id: "mnt-part-001",
        partStockId: "part-002",
        name: "Pastilha de freio dianteira",
        quantity: 6,
        unitValue: 205,
        totalValue: 1230,
      },
      {
        id: "mnt-part-002",
        partStockId: "part-006",
        name: "Amortecedor traseiro",
        quantity: 4,
        unitValue: 480,
        totalValue: 1920,
      },
    ],
  },
  {
    id: "mnt-002",
    vehicleId: "veh-004",
    vehicleName: "Van Escolar 04",
    date: "2026-05-02",
    type: "Preventiva",
    mechanic: "Equipe interna",
    notes: "Revisão programada por quilometragem.",
    totalValue: 1288.5,
    parts: [
      {
        id: "mnt-part-003",
        partStockId: "part-001",
        name: "Filtro de óleo Sprinter",
        quantity: 3,
        unitValue: 82.5,
        totalValue: 247.5,
      },
      {
        id: "mnt-part-004",
        partStockId: "part-005",
        name: "Correia dentada",
        quantity: 1,
        unitValue: 305,
        totalValue: 305,
      },
    ],
  },
  {
    id: "mnt-003",
    vehicleId: "veh-001",
    vehicleName: "Van Executiva 01",
    date: "2026-04-22",
    type: "Preventiva",
    mechanic: "Equipe interna",
    notes: "Troca de filtros e inspeção geral.",
    totalValue: 645.4,
    parts: [
      {
        id: "mnt-part-005",
        partStockId: "part-001",
        name: "Filtro de óleo Sprinter",
        quantity: 2,
        unitValue: 79.9,
        totalValue: 159.8,
      },
    ],
  },
  {
    id: "mnt-004",
    vehicleId: "veh-003",
    vehicleName: "Utilitário Logístico",
    date: "2026-03-15",
    type: "Pneus",
    mechanic: "Pneus Norte Sul",
    notes: "Rodízio e troca de pneus.",
    totalValue: 3290,
    parts: [
      {
        id: "mnt-part-006",
        partStockId: "part-003",
        name: "Pneu 225/75 R16",
        quantity: 4,
        unitValue: 822.5,
        totalValue: 3290,
      },
    ],
  },
  {
    id: "mnt-005",
    vehicleId: "veh-006",
    vehicleName: "Pickup Operacional",
    date: "2026-02-20",
    type: "Corretiva",
    mechanic: "Oficina Rápida Diesel",
    notes: "Correção de ruído em suspensão.",
    totalValue: 1574,
    parts: [
      {
        id: "mnt-part-007",
        partStockId: "part-006",
        name: "Amortecedor traseiro",
        quantity: 2,
        unitValue: 444,
        totalValue: 888,
      },
    ],
  },
  {
    id: "mnt-006",
    vehicleId: "veh-005",
    vehicleName: "Furgão Refrigerado",
    date: "2026-01-19",
    type: "Preventiva",
    mechanic: "Equipe interna",
    notes: "Primeira revisão operacional.",
    totalValue: 812,
    parts: [
      {
        id: "mnt-part-008",
        partStockId: "part-004",
        name: "Óleo 15W40 Diesel",
        quantity: 12,
        unitValue: 34,
        totalValue: 408,
      },
    ],
  },
];

export const demoOilChanges: OilChange[] = [
  {
    id: "oil-001",
    vehicleId: "veh-001",
    vehicleName: "Van Executiva 01",
    oilType: "15W40 Diesel",
    liters: 9,
    valuePerLiter: 34,
    totalValue: 306,
    date: "2026-05-05",
  },
  {
    id: "oil-002",
    vehicleId: "veh-004",
    vehicleName: "Van Escolar 04",
    oilType: "10W40 Semissintético",
    liters: 8,
    valuePerLiter: 39.9,
    totalValue: 319.2,
    date: "2026-04-30",
  },
  {
    id: "oil-003",
    vehicleId: "veh-006",
    vehicleName: "Pickup Operacional",
    oilType: "5W30 Sintético",
    liters: 7,
    valuePerLiter: 52,
    totalValue: 364,
    date: "2026-03-11",
  },
];

export const demoFuelLogs: FuelLog[] = [
  {
    id: "fuel-001",
    vehicleId: "veh-001",
    vehicleName: "Van Executiva 01",
    fuelType: "Diesel S10",
    liters: 162,
    pricePerLiter: 5.96,
    totalValue: 965.52,
    station: "Posto Avenida",
    date: "2026-05-08",
  },
  {
    id: "fuel-002",
    vehicleId: "veh-002",
    vehicleName: "Micro-ônibus Urbano",
    fuelType: "Diesel S10",
    liters: 244,
    pricePerLiter: 5.89,
    totalValue: 1437.16,
    station: "Rede União",
    date: "2026-05-07",
  },
  {
    id: "fuel-003",
    vehicleId: "veh-006",
    vehicleName: "Pickup Operacional",
    fuelType: "Diesel S10",
    liters: 88,
    pricePerLiter: 5.94,
    totalValue: 522.72,
    station: "Posto Avenida",
    date: "2026-04-27",
  },
  {
    id: "fuel-004",
    vehicleId: "veh-005",
    vehicleName: "Furgão Refrigerado",
    fuelType: "Diesel S10",
    liters: 130,
    pricePerLiter: 5.91,
    totalValue: 768.3,
    station: "Auto Posto Central",
    date: "2026-03-30",
  },
];

export const demoServiceMotorcycles: ServiceMotorcycle[] = [
  {
    id: "moto-001",
    model: "CG 160 Cargo",
    brand: "Honda",
    plate: "SVC1A23",
    year: 2024,
    mileage: 18420,
    status: "GARAGE",
    driver: "Igor Martins",
    photoUrl: "",
    notes: "Moto principal para entregas rapidas e apoio operacional.",
  },
  {
    id: "moto-002",
    model: "Factor 150 UBS",
    brand: "Yamaha",
    plate: "MTS8D91",
    year: 2023,
    mileage: 26310,
    status: "IN_SERVICE",
    driver: "Patricia Ramos",
    photoUrl: "",
    notes: "Em roteiro diario de coleta de documentos.",
  },
  {
    id: "moto-003",
    model: "NXR 160 Bros",
    brand: "Honda",
    plate: "RDO4F44",
    year: 2022,
    mileage: 41980,
    status: "MAINTENANCE",
    driver: "Leandro Vieira",
    photoUrl: "",
    notes: "Aguardando revisao de corrente e pneus.",
  },
];

export const demoMotorcycleFines: MotorcycleFine[] = [
  {
    id: "fine-001",
    motorcycleId: "moto-002",
    motorcycleName: "Yamaha Factor 150 UBS",
    motorcyclePlate: "MTS8D91",
    tripId: "trip-002",
    value: 195.23,
    paidAmount: 0,
    paymentStatus: "PENDING",
    paidBy: null,
    authorizedBy: null,
    paidAt: null,
    paymentNotes: null,
    paymentHistory: [],
    reason: "Estacionamento irregular",
    date: "2026-05-04",
    notes: "Aguardando recurso administrativo.",
  },
];

export const demoMotorcycleTrips: MotorcycleTrip[] = [
  {
    id: "trip-001",
    motorcycleId: "moto-001",
    motorcycleName: "Honda CG 160 Cargo",
    motorcyclePlate: "SVC1A23",
    departureAt: "2026-05-08T08:10",
    returnAt: "2026-05-08T11:45",
    driver: "Igor Martins",
    destination: "Centro logistico",
    serviceDone: "Entrega de documentos e pecas leves",
    quantityTransported: 12,
    notes: "Roteiro concluido sem ocorrencias.",
  },
  {
    id: "trip-002",
    motorcycleId: "moto-002",
    motorcycleName: "Yamaha Factor 150 UBS",
    motorcyclePlate: "MTS8D91",
    departureAt: "2026-05-04T13:20",
    returnAt: "2026-05-04T17:10",
    driver: "Patricia Ramos",
    destination: "Unidade Norte",
    serviceDone: "Coleta de malotes administrativos",
    quantityTransported: 8,
    notes: "Houve multa vinculada ao roteiro.",
    fine: demoMotorcycleFines[0],
  },
  {
    id: "trip-003",
    motorcycleId: "moto-001",
    motorcycleName: "Honda CG 160 Cargo",
    motorcyclePlate: "SVC1A23",
    departureAt: "2026-04-21T09:00",
    returnAt: "2026-04-21T12:25",
    driver: "Igor Martins",
    destination: "Oficina parceira",
    serviceDone: "Transporte de notas fiscais",
    quantityTransported: 5,
    notes: "Retorno no prazo.",
  },
];

export const demoFinancialEntries: FinancialEntry[] = [
  {
    id: "fin-001",
    kind: "INCOME",
    category: "Receita operacional",
    description: "Rateio mensal dos cooperados",
    value: 58200,
    date: "2026-05-01",
  },
  {
    id: "fin-002",
    kind: "EXPENSE",
    category: "Manutenção",
    description: "Manutenção corretiva - Micro-ônibus Urbano",
    value: 3849,
    date: "2026-05-06",
    vehicleId: "veh-002",
    vehicleName: "Micro-ônibus Urbano",
  },
  {
    id: "fin-003",
    kind: "EXPENSE",
    category: "Manutenção",
    description: "Revisão programada - Van Escolar 04",
    value: 1288.5,
    date: "2026-05-02",
    vehicleId: "veh-004",
    vehicleName: "Van Escolar 04",
  },
  {
    id: "fin-004",
    kind: "EXPENSE",
    category: "Óleo",
    description: "Troca de óleo - Van Executiva 01",
    value: 306,
    date: "2026-05-05",
    vehicleId: "veh-001",
    vehicleName: "Van Executiva 01",
  },
  {
    id: "fin-005",
    kind: "EXPENSE",
    category: "Combustível",
    description: "Abastecimento - Van Executiva 01",
    value: 965.52,
    date: "2026-05-08",
    vehicleId: "veh-001",
    vehicleName: "Van Executiva 01",
  },
  {
    id: "fin-006",
    kind: "EXPENSE",
    category: "Combustível",
    description: "Abastecimento - Micro-ônibus Urbano",
    value: 1437.16,
    date: "2026-05-07",
    vehicleId: "veh-002",
    vehicleName: "Micro-ônibus Urbano",
  },
  {
    id: "fin-006b",
    kind: "EXPENSE",
    category: "Multas",
    description: "Multa - Yamaha Factor 150 UBS",
    value: 195.23,
    date: "2026-05-04",
    serviceMotorcycleId: "moto-002",
    serviceMotorcycleName: "Yamaha Factor 150 UBS",
  },
  {
    id: "fin-007",
    kind: "INCOME",
    category: "Receita operacional",
    description: "Rateio mensal dos cooperados",
    value: 54800,
    date: "2026-04-01",
  },
  {
    id: "fin-008",
    kind: "EXPENSE",
    category: "Manutenção",
    description: "Troca de filtros - Van Executiva 01",
    value: 645.4,
    date: "2026-04-22",
    vehicleId: "veh-001",
    vehicleName: "Van Executiva 01",
  },
  {
    id: "fin-009",
    kind: "EXPENSE",
    category: "Óleo",
    description: "Troca de óleo - Van Escolar 04",
    value: 319.2,
    date: "2026-04-30",
    vehicleId: "veh-004",
    vehicleName: "Van Escolar 04",
  },
  {
    id: "fin-010",
    kind: "EXPENSE",
    category: "Combustível",
    description: "Abastecimento - Pickup Operacional",
    value: 522.72,
    date: "2026-04-27",
    vehicleId: "veh-006",
    vehicleName: "Pickup Operacional",
  },
  {
    id: "fin-011",
    kind: "INCOME",
    category: "Receita operacional",
    description: "Rateio mensal dos cooperados",
    value: 52300,
    date: "2026-03-01",
  },
  {
    id: "fin-012",
    kind: "EXPENSE",
    category: "Manutenção",
    description: "Troca de pneus - Utilitário Logístico",
    value: 3290,
    date: "2026-03-15",
    vehicleId: "veh-003",
    vehicleName: "Utilitário Logístico",
  },
  {
    id: "fin-013",
    kind: "EXPENSE",
    category: "Óleo",
    description: "Troca de óleo - Pickup Operacional",
    value: 364,
    date: "2026-03-11",
    vehicleId: "veh-006",
    vehicleName: "Pickup Operacional",
  },
  {
    id: "fin-014",
    kind: "EXPENSE",
    category: "Combustível",
    description: "Abastecimento - Furgão Refrigerado",
    value: 768.3,
    date: "2026-03-30",
    vehicleId: "veh-005",
    vehicleName: "Furgão Refrigerado",
  },
  {
    id: "fin-015",
    kind: "INCOME",
    category: "Receita operacional",
    description: "Rateio mensal dos cooperados",
    value: 50200,
    date: "2026-02-01",
  },
  {
    id: "fin-016",
    kind: "EXPENSE",
    category: "Manutenção",
    description: "Correção de suspensão - Pickup Operacional",
    value: 1574,
    date: "2026-02-20",
    vehicleId: "veh-006",
    vehicleName: "Pickup Operacional",
  },
  {
    id: "fin-017",
    kind: "INCOME",
    category: "Receita operacional",
    description: "Rateio mensal dos cooperados",
    value: 48600,
    date: "2026-01-01",
  },
  {
    id: "fin-018",
    kind: "EXPENSE",
    category: "Manutenção",
    description: "Primeira revisão - Furgão Refrigerado",
    value: 812,
    date: "2026-01-19",
    vehicleId: "veh-005",
    vehicleName: "Furgão Refrigerado",
  },
];

export const demoNotifications: AppNotification[] = [
  {
    id: "ntf-001",
    title: "Manutenção em andamento",
    message: "Micro-ônibus Urbano está em manutenção corretiva desde 06/05.",
    type: "WARNING",
    read: false,
    dueDate: "2026-05-12",
    vehicleId: "veh-002",
    vehicleName: "Micro-ônibus Urbano",
    createdAt: "2026-05-06",
  },
  {
    id: "ntf-002",
    title: "Estoque baixo",
    message: "Pastilha de freio dianteira está abaixo do mínimo operacional.",
    type: "DANGER",
    read: false,
    createdAt: "2026-05-07",
  },
  {
    id: "ntf-003",
    title: "Quilometragem crítica",
    message: "Van Escolar 04 ultrapassou o limite recomendado para revisão.",
    type: "WARNING",
    read: true,
    dueDate: "2026-05-15",
    vehicleId: "veh-004",
    vehicleName: "Van Escolar 04",
    createdAt: "2026-05-01",
  },
];

export const demoActivityLogs: ActivityLog[] = [
  {
    id: "log-001",
    userName: "Administrador",
    action: "CREATE",
    entity: "Estoque",
    entityId: "stk-002",
    description: "Entrada de pastilhas de freio registrada no almoxarifado.",
    createdAt: "2026-05-03",
    module: "Estoque",
    date: "2026-05-03",
    time: "08:30",
    ipAddress: "127.0.0.1",
    device: "Navegador corporativo",
  },
  {
    id: "log-002",
    userName: "Administrador",
    action: "CREATE",
    entity: "Motos de Servico",
    entityId: "trip-002",
    description: "Saida de moto com multa vinculada ao financeiro.",
    createdAt: "2026-05-04",
    module: "Motos de Servico",
    date: "2026-05-04",
    time: "13:20",
    ipAddress: "127.0.0.1",
    device: "Navegador corporativo",
  },
];

export const demoAuditTrail: AuditTrailEntry[] = [
  {
    id: "audit-001",
    userName: "Administrador",
    module: "Estoque",
    entityId: "part-002",
    summary: "Administrador atualizou o custo da Pastilha de freio dianteira.",
    oldValue: { unitCost: 181.9 },
    newValue: { unitCost: 189.5 },
    createdAt: "2026-05-03T08:30:00.000Z",
  },
];

export const demoAttachments: Attachment[] = [];
export const demoDeletedItems: DeletedItem[] = [];
export const demoBackupRecords: BackupRecord[] = [];

export const demoCompanySettings: CompanySettings = {
  cooperativeName: "CoopFleet",
  logoUrl: "",
  theme: "premium-dark",
  currency: "BRL",
  timezone: "America/Sao_Paulo",
  backupFrequency: "daily",
  backupRetentionDays: 30,
  notificationsEnabled: true,
  sessionTimeoutMinutes: 480,
};

export function createDemoDataset(): Dataset {
  return {
    users: structuredClone(demoUsers),
    vehicles: structuredClone(demoVehicles),
    maintenances: structuredClone(demoMaintenances),
    oilChanges: structuredClone(demoOilChanges),
    financialEntries: structuredClone(demoFinancialEntries),
    suppliers: structuredClone(demoSuppliers),
    partStock: structuredClone(demoPartStock),
    stockMovements: structuredClone(demoStockMovements),
    fuelLogs: structuredClone(demoFuelLogs),
    notifications: structuredClone(demoNotifications),
    serviceMotorcycles: structuredClone(demoServiceMotorcycles),
    motorcycleTrips: structuredClone(demoMotorcycleTrips),
    motorcycleFines: structuredClone(demoMotorcycleFines),
    activityLogs: structuredClone(demoActivityLogs),
    auditTrail: structuredClone(demoAuditTrail),
    attachments: structuredClone(demoAttachments),
    deletedItems: structuredClone(demoDeletedItems),
    backupRecords: structuredClone(demoBackupRecords),
    companySettings: structuredClone(demoCompanySettings),
  };
}
